// ─────────────────────────────────────────────────────────────────────────────
// Token store — the persistence layer for the transcript-ingest pipeline.
//
// PORTED VERBATIM-IN-MEANING from the token-relevant half of
// apps/server/src/db.ts: `insertTokenEvent`, the `transcript_offsets`
// accessors, and `findTokenEventNear`.
//
// DRIVER NOTE: these statements run against the RAW `bun:sqlite` handle that
// the Drizzle client wraps (exported as `sqlite` from ../db/client). Same
// single WAL connection, same `command-center.db`, same schema/migrations
// generated by Drizzle — we just keep the SQL verbatim here. This is a
// deliberate parity decision: the dedupe (`INSERT OR IGNORE` against the
// `UNIQUE(transcript_file, inode, transcript_line_offset)` constraint) and the
// NULL-safe / inode-wildcard semantics are audited and non-obvious; porting
// the exact SQL guarantees byte-compatibility with the legacy endpoints rather
// than re-deriving it through the query builder.
// ─────────────────────────────────────────────────────────────────────────────

import { sqlite as db } from '../db/client';

export interface TokenEventRow {
  id?: number;
  ts: number;
  session_id: string;
  cwd: string | null;
  git_branch: string | null;
  model: string;
  input: number;
  cache_read: number;
  cache_write_5m: number;
  cache_write_1h: number;
  output: number;
  cost_usd: number | null;
  request_id: string | null;
  transcript_file: string;
  transcript_line_offset: number;
  // Stable file identity (typically the OS inode number) at the time the
  // row was ingested. Optional on the type because:
  //   1. Legacy rows persisted before the inode migration are stored as NULL.
  //   2. The ingest layer is the only producer that knows the inode; tests
  //      and ad-hoc inserts may omit it.
  // When present, two rows with the same (transcript_file, offset) but
  // different inodes are treated as distinct (file rotation case).
  inode?: number | null;
}

export function insertTokenEvent(row: TokenEventRow): TokenEventRow | null {
  const stmt = db.prepare(`
    INSERT OR IGNORE INTO token_events
      (ts, session_id, cwd, git_branch, model, input, cache_read, cache_write_5m, cache_write_1h, output, cost_usd, request_id, transcript_file, transcript_line_offset, inode)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);
  const result = stmt.run(
    row.ts,
    row.session_id,
    row.cwd,
    row.git_branch,
    row.model,
    row.input,
    row.cache_read,
    row.cache_write_5m,
    row.cache_write_1h,
    row.output,
    row.cost_usd,
    row.request_id,
    row.transcript_file,
    row.transcript_line_offset,
    row.inode ?? null
  );
  if (result.changes === 0) return null;
  return { ...row, id: Number(result.lastInsertRowid) };
}

export interface TranscriptOffsetRow {
  offset: number;
  inode: number | null;
}

// Returns just the persisted byte offset for `file`. Kept for callers that
// don't care about inode (e.g. legacy code paths). New callers should prefer
// `getTranscriptOffsetRow` so they can validate the inode against the
// current on-disk file and reset on mismatch.
export function getTranscriptOffset(file: string): number {
  return getTranscriptOffsetRow(file)?.offset ?? 0;
}

// Returns the persisted offset row including stored inode. NULL inode means
// the row was written before the inode migration — callers should treat NULL
// as a wildcard (path-only match) to preserve legacy behaviour.
export function getTranscriptOffsetRow(file: string): TranscriptOffsetRow | null {
  const stmt = db.prepare('SELECT offset, inode FROM transcript_offsets WHERE file = ?');
  const row = stmt.get(file) as { offset: number; inode: number | null } | undefined;
  if (!row) return null;
  return { offset: row.offset, inode: row.inode };
}

export function setTranscriptOffset(file: string, offset: number, inode?: number | null): void {
  const stmt = db.prepare(`
    INSERT INTO transcript_offsets (file, offset, updated_at, inode) VALUES (?, ?, ?, ?)
    ON CONFLICT(file) DO UPDATE SET
      offset = excluded.offset,
      updated_at = excluded.updated_at,
      inode = excluded.inode
  `);
  stmt.run(file, offset, Date.now(), inode ?? null);
}

// Used by the transcript-ingest unlink handler — drop the row when its
// underlying file is removed so the offsets table doesn't grow forever.
export function deleteTranscriptOffset(file: string): void {
  const stmt = db.prepare('DELETE FROM transcript_offsets WHERE file = ?');
  stmt.run(file);
}

// Used by the /api/tokens/event REST fallback in the client's findCostForEvent.
// Returns the closest token_events row (by |ts - target|) within the window,
// or null if no row is within window ms.
export function findTokenEventNear(
  sessionId: string,
  ts: number,
  windowMs: number,
): TokenEventRow | null {
  const stmt = db.prepare(`
    SELECT * FROM token_events
    WHERE session_id = ? AND ABS(ts - ?) <= ?
    ORDER BY ABS(ts - ?) ASC
    LIMIT 1
  `);
  const row = stmt.get(sessionId, ts, windowMs, ts) as TokenEventRow | undefined;
  return row ?? null;
}
